# Generated by Django 3.2.19 on 2023-07-18 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Travelapp', '0002_blogt'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='blogt',
            new_name='btable',
        ),
    ]
