# Generated by Django 3.2.19 on 2023-07-18 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='blogt',
        ),
    ]
